
CREATE TABLE public.police_contacts (
contact_id VARCHAR(10) PRIMARY KEY,
urban_id VARCHAR(12) REFERENCES public.Urban_Areas(Urban_id) NOT NULL,
officer_name VARCHAR (30),
contact_number NUMERIC (9),
email VARCHAR (30)
);

INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_001', 'Urban_001', 'Carmen Mendoza', 656500745, 'Police_email_001@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_002', 'Urban_002', 'Sergio Mendez', 112233445, 'Police_email_002@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_003', 'Urban_003', 'Carolina Ortega', 998877665, 'Police_email_003@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_004', 'Urban_004', 'Emilio Silva', 334455667, 'Police_email_004@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_005', 'Urban_005', 'Beatriz Castro', 778899001, 'Police_email_005@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_006', 'Urban_006', 'Raul Varela', 223344556, 'Police_email_006@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_007', 'Urban_007', 'Adriana Navarro', 667788990, 'Police_email_007@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_008', 'Urban_008', 'Victor Mendoza', 445566778, 'Police_email_008@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_009', 'Urban_009', 'Clara Paredes', 889900112, 'Police_email_009@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_010', 'Urban_010', 'Alberto Rojas', 554433221, 'Police_email_010@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_011', 'Urban_011', 'Natalia Salazar', 001122334, 'Police_email_011@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_012', 'Urban_012', 'Arturo Cabrera', 997766554, 'Police_email_012@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_013', 'Urban_013', 'Mariana Soto', 889922211, 'Police_email_013@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_014', 'Urban_014', 'Hugo Peralta', 332211445, 'Police_email_014@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_015', 'Urban_015', 'Laura Jimenez', 554477996, 'Police_email_015@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_016', 'Urban_016', 'Ernesto Santos', 112233556, 'Police_email_016@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_017', 'Urban_017', 'Susana Morales', 667788112, 'Police_email_017@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_018', 'Urban_018', 'Raúl Delgado', 443322667, 'Police_email_018@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_019', 'Urban_019', 'Gabriella Fuentes', 887766554, 'Police_email_019@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_020', 'Urban_020', 'Fernando Rios', 665544332, 'Police_email_020@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_021', 'Urban_021', 'Belen Duarte', 221133445, 'Police_email_021@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_022', 'Urban_022', 'Javier Medina', 778899112, 'Police_email_022@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_023', 'Urban_023', 'Lorena Chavez', 445566001, 'Police_email_023@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_024', 'Urban_024', 'Hector Flores', 112334455, 'Police_email_024@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_025', 'Urban_025', 'Isabel Gallegos', 334455889, 'Police_email_025@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_026', 'Urban_026', 'Ricardo Castillo', 778899445, 'Police_email_026@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_027', 'Urban_027', 'Paula Herrera', 554433667, 'Police_email_027@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_028', 'Urban_028', 'Esteban Cardenas', 112223334, 'Police_email_028@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_029', 'Urban_029', 'Alejandra León', 445566778, 'Police_email_029@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_030', 'Urban_030', 'Octavio Aguilar', 556677990, 'Police_email_030@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_031', 'Urban_031', 'Renata Suarez', 334455667, 'Police_email_031@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_032', 'Urban_032', 'Sergio Pacheco', 778899001, 'Police_email_032@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_033', 'Urban_033', 'Valeria Peña', 223344556, 'Police_email_033@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_034', 'Urban_034', 'Ivan Vargas', 990011223, 'Police_email_034@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_035', 'Urban_035', 'Carla Valdez', 445566778, 'Police_email_035@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_036', 'Urban_036', 'Francisco Roman', 889900112, 'Police_email_036@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_037', 'Urban_037', 'Celeste Palacios', 554433221, 'Police_email_037@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_038', 'Urban_038', 'Martin Robles', 001122334, 'Police_email_038@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_039', 'Urban_039', 'Monica Cervantes', 997766554, 'Police_email_039@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_040', 'Urban_040', 'Guillermo Serrano', 889922211, 'Police_email_040@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_041', 'Urban_041', 'Adrianna Beltran', 665544778, 'Police_email_041@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_042', 'Urban_042', 'Juan Carlos Ponce', 332211445, 'Police_email_042@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_043', 'Urban_043', 'Camila Montes', 554477996, 'Police_email_043@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_044', 'Urban_044', 'Miguel Angel Zavala', 112233556, 'Police_email_044@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_045', 'Urban_045', 'Antonia Rangel', 443322667, 'Police_email_045@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_046', 'Urban_046', 'Jorge Mercado', 887766554, 'Police_email_046@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_047', 'Urban_047', 'Marisol Trejo', 221133445, 'Police_email_047@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_048', 'Urban_048', 'Samuel Cisneros', 778899112, 'Police_email_048@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_049', 'Urban_049', 'Valeria Maldonado', 667788223, 'Police_email_049@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_050', 'Urban_050', 'Alejandro Torres', 445566001, 'Police_email_050@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_051', 'Urban_051', 'Ana Sofia Nieves', 656517705, 'Police_email_051@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_052', 'Urban_052', 'Luis Manuel Ríos', 112334455, 'Police_email_052@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_053', 'Urban_053', 'Isabel Mora', 334455889, 'Police_email_053@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_054', 'Urban_054', 'Oscar Quintero', 554433667, 'Police_email_054@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_055', 'Urban_055', 'Vanessa Fuentes', 778899445, 'Police_email_055@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_056', 'Urban_056', 'Cristian Juarez', 112223334, 'Police_email_056@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_057', 'Urban_057', 'Regina Villa', 445566778, 'Police_email_057@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_058', 'Urban_058', 'Juan Pablo Salinas', 556677990, 'Police_email_058@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_059', 'Urban_059', 'Alba Mendoza', 334455667, 'Police_email_059@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_060', 'Urban_060', 'Gabriel Roldan', 778899001, 'Police_email_060@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_061', 'Urban_061', 'Adrian Alvarado', 223344556, 'Police_email_061@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_061', 'Urban_062', 'Diana Cruz', 667788990, 'Police_email_062@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_062', 'Urban_063', 'Javier Ramos', 990011223, 'Police_email_063@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_063', 'Urban_064', 'Aurora Calderon', 445566778, 'Police_email_064@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_064', 'Urban_065', 'Emiliano Almonte', 889900112, 'Police_email_065@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_065', 'Urban_066', 'Mariana Ríos', 554433221, 'Police_email_066@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_066', 'Urban_067', 'Arturo Cisneros', 997766554, 'Police_email_067@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_067', 'Urban_068', 'Leticia Vela', 001122334, 'Police_email_068@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_068', 'Urban_069', 'Rafael Guzman', 889922211, 'Police_email_069@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_069', 'Urban_070', 'Eloisa Mendoza', 332211445, 'Police_email_070@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_070', 'Urban_071', 'Alejandro Vega', 665544778, 'Police_email_071@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_071', 'Urban_072', 'Catalina Leal', 554477996, 'Police_email_072@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_072', 'Urban_073', 'Roberto Gálvez', 112233556, 'Police_email_073@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_073', 'Urban_074', 'Marlene Sánchez', 667788112, 'Police_email_074@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_074', 'Urban_075', 'Sergio León', 443322667, 'Police_email_075@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_075', 'Urban_076', 'Valentina Salas', 887766554, 'Police_email_076@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_076', 'Urban_077', 'Ignacio Paredes', 665544332, 'Police_email_077@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_077', 'Urban_078', 'Gabriela Márquez', 221133445, 'Police_email_078@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_078', 'Urban_079', 'Carlos Arroyo', 778899112, 'Police_email_079@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_079', 'Urban_080', 'Patricia Espinosa', 667788223, 'Police_email_080@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_080', 'Urban_081', 'Orlando Pacheco', 445566001, 'Police_email_081@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_081', 'Urban_082', 'Yesenia Méndez', 112334455, 'Police_email_082@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_082', 'Urban_083', 'Daniel Robledo', 334455889, 'Police_email_083@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_083', 'Urban_084', 'Maria Elena Barrera', 778899445, 'Police_email_084@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_084', 'Urban_085', 'Eduardo Hidalgo', 554433667, 'Police_email_085@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_085', 'Urban_086', 'Alma González', 112223334, 'Police_email_086@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_086', 'Urban_087', 'Mauricio Fuentes', 445566778, 'Police_email_087@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_087', 'Urban_088', 'Adriana Acosta', 334455667, 'Police_email_088@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_088', 'Urban_089', 'Ernesto Téllez', 778899001, 'Police_email_089@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_089', 'Urban_090', 'Isabela Beltrán', 223344556, 'Police_email_090@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_090', 'Urban_091', 'Juan José Paredes', 667788990, 'Police_email_091@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_091', 'Urban_092', 'Natalia Serrano', 990011223, 'Police_email_092@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_092', 'Urban_093', 'Gerardo Del Toro', 445566778, 'Police_email_093@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_093', 'Urban_094', 'Veronica Medina', 889900112, 'Police_email_094@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_094', 'Urban_095', 'Adrian Sánchez', 554433221, 'Police_email_095@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_095', 'Urban_096', 'Brenda Pacheco', 001122334, 'Police_email_096@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_096', 'Urban_097', 'Juan Carlos Cervantes', 997766554, 'Police_email_097@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_097', 'Urban_098', 'Daniela Méndez', 332211445, 'Police_email_098@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_098', 'Urban_099', 'Francisco Solís', 665544778, 'Police_email_099@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_099', 'Urban_100', 'Angela Navarro', 554477996, 'Police_email_100@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_001', 'Urban_101', 'Oscar Mora', 112233556, 'Police_email_101@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_002', 'Urban_102', 'Mariana Rocha', 667788112, 'Police_email_102@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_003', 'Urban_103', 'Alejandro Sierra', 443322667, 'Police_email_103@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_004', 'Urban_104', 'Regina Ortega', 887766554, 'Police_email_104@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_005', 'Urban_105', 'Mauricio Guzmán', 665544332, 'Police_email_105@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_006', 'Urban_106', 'Daniela León', 221133445, 'Police_email_106@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_007', 'Urban_107', 'Gustavo Ríos', 778899112, 'Police_email_107@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_008', 'Urban_108', 'Susana Lugo', 667788223, 'Police_email_108@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_009', 'Urban_109', 'Carlos Estrada', 445566001, 'Police_email_109@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_010', 'Urban_110', 'Carolina Ochoa', 112334455, 'Police_email_110@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_011', 'Urban_111', 'Lorenzo Cárdenas', 334455889, 'Police_email_111@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_012', 'Urban_112', 'Maria Teresa Juarez', 778899445, 'Police_email_112@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_013', 'Urban_113', 'Agustin Rangel', 554433667, 'Police_email_113@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_014', 'Urban_114', 'Claudia Cisneros', 112223334, 'Police_email_114@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_015', 'Urban_115', 'Julio Maldonado', 445566778, 'Police_email_115@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_016', 'Urban_116', 'Elena Hernández', 556677990, 'Police_email_116@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_017', 'Urban_117', 'Rodrigo Castillo', 334455667, 'Police_email_117@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_018', 'Urban_118', 'Fabiola Morales', 778899001, 'Police_email_118@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_019', 'Urban_119', 'Adrian Soto', 223344556, 'Police_email_119@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_020', 'Urban_120', 'Gabriela Alvarado', 667788990, 'Police_email_120@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_021', 'Urban_121', 'Francisco Salgado', 990011223, 'Police_email_121@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_022', 'Urban_122', 'Vanessa Vargas', 445566778, 'Police_email_122@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_023', 'Urban_123', 'Gustavo Medina', 554433221, 'Police_email_123@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_024', 'Urban_124', 'Liliana Trejo', 889900112, 'Police_email_124@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_025', 'Urban_125', 'Tomas Contreras', 001122334, 'Police_email_125@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_026', 'Urban_126', 'Laura Soto', 997766554, 'Police_email_126@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_027', 'Urban_127', 'Esteban Ríos', 889922211, 'Police_email_127@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_028', 'Urban_128', 'Brenda Gallegos', 332211445, 'Police_email_128@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_029', 'Urban_129', 'Ramiro Valdez', 665544778, 'Police_email_129@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_030', 'Urban_130', 'Karla Carrillo', 554477996, 'Police_email_130@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_031', 'Urban_131', 'Ricardo Fuentes', 112233556, 'Police_email_131@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_032', 'Urban_132', 'Aurora Díaz', 667788112, 'Police_email_132@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_033', 'Urban_133', 'Felix Herrera', 443322667, 'Police_email_133@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_034', 'Urban_134', 'Dalia Mendoza', 887766554, 'Police_email_134@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_035', 'Urban_135', 'Miguel Angel Ríos', 665544332, 'Police_email_135@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_036', 'Urban_136', 'Silvia Martínez', 221133445, 'Police_email_136@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_037', 'Urban_137', 'Hector Varela', 554433667, 'Police_email_137@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_038', 'Urban_138', 'Sonia Peralta', 667788223, 'Police_email_138@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_039', 'Urban_139', 'Victor Cabrera', 445566001, 'Police_email_139@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_040', 'Urban_140', 'Alma García', 112223334, 'Police_email_140@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_041', 'Urban_141', 'Julio César Vargas', 445566778, 'Police_email_141@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_042', 'Urban_142', 'Rosario Méndez', 556677990, 'Police_email_142@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_043', 'Urban_143', 'Carlos Palacios', 334455667, 'Police_email_143@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_044', 'Urban_144', 'Veronica Serrano', 778899001, 'Police_email_144@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_045', 'Urban_145', 'Jorge Rojas', 223344556, 'Police_email_145@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_046', 'Urban_146', 'Vanessa Silva', 667788990, 'Police_email_146@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_047', 'Urban_147', 'Salvador Ríos', 990011223, 'Police_email_147@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_048', 'Urban_148', 'Maribel Nava', 445566778, 'Police_email_148@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_049', 'Urban_149', 'Juan Francisco García', 889900112, 'Police_email_149@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_050', 'Urban_150', 'Estela Ortega', 001122334, 'Police_email_150@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_051', 'Urban_151', 'Edgar Cisneros', 874259361, 'Police_email_151@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_052', 'Urban_152', 'Rosa María Salgado', 502648913, 'Police_email_152@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_053', 'Urban_153', 'Leonardo Vargas', 719836245, 'Police_email_153@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_054', 'Urban_154', 'Adriana Zavala', 631594820, 'Police_email_154@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_055', 'Urban_155', 'Juan Pablo Fuentes', 985267341, 'Police_email_155@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_056', 'Urban_156', 'Diana Cervantes', 168753492, 'Police_email_156@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_057', 'Urban_157', 'Miguel Angel Pacheco', 324178965, 'Police_email_157@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_058', 'Urban_158', 'Adriana Morales', 796415238, 'Police_email_158@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_059', 'Urban_159', 'Gerardo Mendoza', 796415238, 'Police_email_159@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_060', 'Urban_160', 'Alma Rosa León', 247861539, 'Police_email_160@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_061', 'Urban_161', 'Alberto Sánchez', 431597682, 'Police_email_161@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_061', 'Urban_162', 'Brenda Alvarado', 856349210, 'Police_email_162@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_062', 'Urban_163', 'Luis Antonio Méndez', 972185634, 'Police_email_163@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_063', 'Urban_164', 'Celeste Juarez', 305974186, 'Police_email_164@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_064', 'Urban_165', 'Daniel Martínez', 619482357, 'Police_email_165@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_065', 'Urban_166', 'Lourdes Beltrán', 740216859, 'Police_email_166@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_066', 'Urban_167', 'Francisco Javier Ríos', 158347692, 'Police_email_167@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_067', 'Urban_168', 'Marta González', 496823571, 'Police_email_168@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_068', 'Urban_169', 'Sergio Salinas', 287631945, 'Police_email_169@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_069', 'Urban_170', 'Isabela Palacios', 513794628, 'Police_email_170@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_070', 'Urban_171', 'Victor Manuel Zavala', 690542813, 'Police_email_171@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_071', 'Urban_172', 'Patricia Cisneros', 437289156, 'Police_email_172@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_072', 'Urban_173', 'Esteban Vargas', 871356249, 'Police_email_173@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_073', 'Urban_174', 'Alejandra Rocha', 254918763, 'Police_email_174@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_074', 'Urban_175', 'Guillermo Ríos', 368725194, 'Police_email_175@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_075', 'Urban_176', 'Susana Cervantes', 942613578, 'Police_email_176@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_076', 'Urban_177', 'Hector Salgado', 605137824, 'Police_email_177@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_077', 'Urban_178', 'Carla Beltrán', 139824657, 'Police_email_178@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_078', 'Urban_179', 'Javier Robles', 718463925, 'Police_email_179@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_079', 'Urban_180', 'Isabel Solís', 927581346, 'Police_email_180@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_080', 'Urban_181', 'Rafael Mendoza', 684295713, 'Police_email_181@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_081', 'Urban_182', 'Cristina Méndez', 351679482, 'Police_email_182@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_082', 'Urban_183', 'Marcos Carrasco', 876594231, 'Police_email_183@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_083', 'Urban_184', 'Alejandra Ramírez', 520743186, 'Police_email_184@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_084', 'Urban_185', 'Gabriel Serrano', 463128579, 'Police_email_185@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_085', 'Urban_186', 'Inés Peralta', 189657342, 'Police_email_186@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_086', 'Urban_187', 'Ricardo Núñez', 397816524, 'Police_email_187@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_087', 'Urban_188', 'Claudia García', 642935718, 'Police_email_188@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_088', 'Urban_189', 'Mauricio Soto', 815472963, 'Police_email_189@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_089', 'Urban_190', 'Valeria Jiménez', 276359841, 'Police_email_190@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_090', 'Urban_191', 'Andrés Rojas', 359284176, 'Police_email_191@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_091', 'Urban_192', 'Elena Morales', 784136295, 'Police_email_192@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_092', 'Urban_193', 'José Luis Vargas', 146972538, 'Police_email_193@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_093', 'Urban_194', 'Marina Varela', 538621794, 'Police_email_194@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_094', 'Urban_195', 'Martín Ríos', 927415683, 'Police_email_195@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_095', 'Urban_196', 'Fernanda Maldonado', 615387249, 'Police_email_196@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_096', 'Urban_197', 'Javier Castillo', 492751836, 'Police_email_197@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_097', 'Urban_198', 'Gabriela Pacheco', 847963120, 'Police_email_198@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_098', 'Urban_199', 'Roberto Delgado', 321846597, 'Police_email_199@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_099', 'Urban_200', 'Vanessa Torres', 659713284, 'Police_email_200@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_001', 'Urban_201', 'Luisa Ríos', 983524617, 'Police_email_201@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_002', 'Urban_202', 'Diego Herrera', 274681953, 'Police_email_202@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_003', 'Urban_203', 'Laura Sánchez', 548396172, 'Police_email_203@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_004', 'Urban_204', 'Andrés Paredes', 716249835, 'Police_email_204@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_005', 'Urban_205', 'Alejandro Beltrán', 835172469, 'Police_email_205@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_006', 'Urban_206', 'Valentina Rojas', 193468752, 'Police_email_206@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_007', 'Urban_207', 'Pedro Soto', 462357198, 'Police_email_207@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_008', 'Urban_208', 'Antonia Martínez', 589641327, 'Police_email_208@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_009', 'Urban_209', 'Ricardo Castro', 124785936, 'Police_email_209@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_010', 'Urban_210', 'Isabel Serrano', 397526184, 'Police_email_210@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_011', 'Urban_211', 'Mateo Fuentes', 671893245, 'Police_email_211@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_012', 'Urban_212', 'Adriana Vargas', 854312769, 'Police_email_212@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_013', 'Urban_213', 'Carlos Maldonado', 236974518, 'Police_email_213@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_014', 'Urban_214', 'Ana Belén Ríos', 598647321, 'Police_email_214@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_015', 'Urban_215', 'Daniel Navarro', 413289765, 'Police_email_215@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_016', 'Urban_216', 'Elena Salinas', 762154389, 'Police_email_216@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_017', 'Urban_217', 'Jorge Varela', 948736251, 'Police_email_217@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_018', 'Urban_218', 'Catalina Ortega', 125943678, 'Police_email_218@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_019', 'Urban_219', 'Sebastián Cabrera', 387621945, 'Police_email_219@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_020', 'Urban_220', 'Gabriela Ríos', 594178362, 'Police_email_220@example.com');
INSERT INTO police_contacts (contact_id, urban_id, officer_name, contact_number, email) VALUES ('Police_021', 'Urban_221', 'Javier Moreno', 819465723, 'Police_email_221@example.com');

COMMIT;
